### ISSUE TITLE
Override Delay time

### ISSUE THREAD

**Issue by nishant-befree** [ericprieto/simply-toast#4]
How to override default delay time to 0 or 10000 ,

$.simplyToast("message","type","options{delay:0}");

please advice

**Comment by ericprieto** [comment]
You already can do that!

And if you want to overwrite the default delay time (4000 ms), you can do

`$.simplyToast.defaultOptions.delay = 10000`

**Comment by ericprieto** [comment]
You already can do that!

And if you want to overwrite the default delay time (4000 ms), you can do

`$.simplyToast.defaultOptions.delay = 10000`
