### ISSUE TITLE
Example not accessable

### ISSUE THREAD

**Issue by ypid** [ericprieto/simply-toast#5]
http://ericprieto.com/freebie/simply-toast/

BTW: Your simply toast looks amazing. Exactly what I was looking for :smile:

**Comment by ericprieto** [comment]
Hey mate!

I moved the example page to codepen.io, you can access it here http://codepen.io/ericprieto/pen/OPKjed

Thank you very much for the compliment, let me know if you have any doubts or ideas for enhancement!

**Comment by ypid** [comment]
The project description (on the top), https://github.com/ericprieto/simply-toast does still link to the old location.
