### ISSUE TITLE
support chrome only?

### ISSUE THREAD

**Issue by ileadu** [ericprieto/simply-toast#6]
I test on the following platform: 
Ubuntu 14.04 Firefox 39 Fail
Windows 8.1 IE11 Fail
Windows 8.1 Chrome OK

Firefox and IE response [object Object]

**Comment by ileadu** [comment]
I use simply-toast.min.js and get the error.
But I use simply-toast.js okay. no error.

**Comment by ygorlazaro** [comment]
I don't know if this issue it's still valid, but here simply-toast is working in Firefox, Chrome and IE9+ for sure.

**Comment by ericprieto** [comment]
@ygorlazaro thank you for testing! :+1:

**Comment by ygorlazaro** [comment]
My pleasure! :wink:
